In [1]:
import osmnx as ox
import geopandas as gpd
import pandas as pd

In [2]:
def clean_gdf_for_saving(gdf):
    for col in gdf.columns:
        # lists to strings
        if gdf[col].apply(lambda x: isinstance(x, list)).any():
            gdf[col] = gdf[col].astype(str)
    return gdf

def get_districts(city_name):
    gdf = ox.geometries_from_place(city_name, tags={'boundary': 'administrative', 'admin_level': '9'})
    gdf_cleaned = clean_gdf_for_saving(gdf)
    
    return gdf_cleaned

## Москва

In [19]:
%%time
stp_districts_gdf_msk = get_districts("Moscow, Russia")

C:\Users\elysi\AppData\Local\Temp\ipykernel_16884\3003042763.py:14: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  gdf = ox.geometries_from_place(city_name, tags={'boundary': 'administrative', 'admin_level': '9'})

CPU times: total: 16 s
Wall time: 23.1 s

In [20]:
stp_districts_gdf_msk.shape

(2656, 550)

In [21]:
stp_districts_gdf_msk.head(5)

                      note                                           geometry  \
element_type osmid
way          38210564  NaN  LINESTRING (37.04563 55.14217, 37.04410 55.142...
             38218993  NaN  LINESTRING (37.21667 55.62195, 37.21739 55.621...
             38220617  NaN  LINESTRING (37.53423 55.94402, 37.53055 55.943...
             39991331  NaN  LINESTRING (37.51850 55.75258, 37.52023 55.750...
             40014414  NaN  LINESTRING (37.36889 55.77304, 37.36882 55.772...

                      highway addr:country addr:district addr:region  \
element_type osmid
way          38210564     NaN          NaN           NaN         NaN
             38218993     NaN          NaN           NaN         NaN
             38220617     NaN          NaN           NaN         NaN
             39991331     NaN          NaN           NaN         NaN
             40014414     NaN          NaN           NaN         NaN

                      contact:website int_name    name     name:ar  ...  \
element_type osmid                                                  ...
way          38210564             NaN      NaN     NaN         NaN  ...
             38218993             NaN      NaN     NaN         NaN  ...
             38220617             NaN      NaN     NaN         NaN  ...
             39991331             NaN      NaN  Москва  نهر موسكفا  ...
             40014414             NaN      NaN     NaN         NaN  ...

                      official_name:nl official_name:ru official_name:sk  \
element_type osmid
way          38210564              NaN              NaN              NaN
             38218993              NaN              NaN              NaN
             38220617              NaN              NaN              NaN
             39991331              NaN              NaN              NaN
             40014414              NaN              NaN              NaN

                      official_name:uk official_name:yi old_short_name  \
element_type osmid
way          38210564              NaN              NaN            NaN
             38218993              NaN              NaN            NaN
             38220617              NaN              NaN            NaN
             39991331              NaN              NaN            NaN
             40014414              NaN              NaN            NaN

                      old_short_name:en old_short_name:ru short_name:ru  \
element_type osmid
way          38210564               NaN               NaN           NaN
             38218993               NaN               NaN           NaN
             38220617               NaN               NaN           NaN
             39991331               NaN               NaN           NaN
             40014414               NaN               NaN           NaN

                      source:start_date
element_type osmid
way          38210564               NaN
             38218993               NaN
             38220617               NaN
             39991331               NaN
             40014414               NaN

[5 rows x 550 columns]

In [22]:
columns_gdf = stp_districts_gdf_msk.columns.to_list()

In [23]:
stp_districts_gdf_msk.admin_level.value_counts()

8    1755
5     455
4     406
6      35
9       3
2       1
3       1
Name: admin_level, dtype: int64

In [24]:
districts_polygons_gdf_msk = stp_districts_gdf_msk[(stp_districts_gdf_msk.geometry.type == 'Polygon') | (stp_districts_gdf_msk.geometry.type == 'MultiPolygon')]

In [25]:
districts_polygons_gdf_msk.shape

(184, 550)

In [26]:
districts_polygons_gdf_msk.head(5)

                      note                                           geometry  \
element_type osmid
way          75589035  NaN  POLYGON ((36.90075 55.31486, 36.90128 55.31396...
relation     51490     NaN  POLYGON ((35.16746 55.98005, 35.16919 55.97986...
             81995     NaN  POLYGON ((33.44193 54.05296, 33.44188 54.05323...
             102269    NaN  MULTIPOLYGON (((36.90075 55.31486, 36.90128 55...
             181165    NaN  POLYGON ((37.04563 55.14217, 37.04482 55.14338...

                      highway addr:country addr:district         addr:region  \
element_type osmid
way          75589035     NaN          NaN           NaN                 NaN
relation     51490        NaN           RU           NaN                 NaN
             81995        NaN           RU           NaN                 NaN
             102269       NaN           RU           NaN                 NaN
             181165       NaN           RU           NaN  Московская область

                      contact:website int_name                   name  \
element_type osmid
way          75589035             NaN      NaN                    NaN
relation     51490                NaN      NaN     Московская область
             81995                NaN      NaN      Калужская область
             102269               NaN      NaN                 Москва
             181165               NaN      NaN  городской округ Чехов

                            name:ar  ... official_name:nl official_name:ru  \
element_type osmid                   ...
way          75589035           NaN  ...              NaN              NaN
relation     51490     محافظة موسكو  ...              NaN              NaN
             81995              NaN  ...              NaN              NaN
             102269             NaN  ...              NaN              NaN
             181165             NaN  ...              NaN              NaN

                      official_name:sk official_name:uk official_name:yi  \
element_type osmid
way          75589035              NaN              NaN              NaN
relation     51490                 NaN              NaN              NaN
             81995                 NaN              NaN              NaN
             102269                NaN              NaN              NaN
             181165                NaN              NaN              NaN

                      old_short_name old_short_name:en old_short_name:ru  \
element_type osmid
way          75589035            NaN               NaN               NaN
relation     51490               NaN               NaN               NaN
             81995               NaN               NaN               NaN
             102269              NaN               NaN               NaN
             181165              NaN               NaN               NaN

                      short_name:ru source:start_date
element_type osmid
way          75589035           NaN               NaN
relation     51490              NaN               NaN
             81995              NaN               NaN
             102269             NaN               NaN
             181165             NaN               NaN

[5 rows x 550 columns]

In [27]:
filtered_gdf_msk = districts_polygons_gdf_msk[districts_polygons_gdf_msk['name'].fillna('').str.contains('административный')]

In [28]:
#filtered_gdf_msk = filtered_gdf_msk[filtered_gdf_msk['addr:region'].fillna('').str.contains('Москва')]

In [29]:
filtered_gdf_msk.shape

(12, 550)

In [30]:
filtered_gdf_msk.head(5)

                     note                                           geometry  \
element_type osmid
relation     226149   NaN  MULTIPOLYGON (((36.90808 55.74875, 36.90939 55...
             2263058  NaN  POLYGON ((37.08750 55.59055, 37.08794 55.59070...
             2263059  NaN  MULTIPOLYGON (((36.90075 55.31486, 36.90128 55...
             162903   NaN  MULTIPOLYGON (((37.36986 55.90820, 37.36862 55...
             446092   NaN  POLYGON ((37.33566 55.84525, 37.33300 55.84528...

                     highway addr:country addr:district addr:region  \
element_type osmid
relation     226149      NaN           RU           NaN      Москва
             2263058     NaN           RU           NaN      Москва
             2263059     NaN           RU           NaN      Москва
             162903      NaN           RU           NaN      Москва
             446092      NaN           RU           NaN      Москва

                              contact:website int_name  \
element_type osmid
relation     226149                       NaN      NaN
             2263058                      NaN      NaN
             2263059                      NaN      NaN
             162903                       NaN      NaN
             446092   http://www.szao.mos.ru/      NaN

                                                        name name:ar  ...  \
element_type osmid                                                    ...
relation     226149          Западный административный округ     NaN  ...
             2263058   Новомосковский административный округ     NaN  ...
             2263059         Троицкий административный округ     NaN  ...
             162903          Северный административный округ     NaN  ...
             446092   Северо-Западный административный округ     NaN  ...

                     official_name:nl official_name:ru official_name:sk  \
element_type osmid
relation     226149               NaN              NaN              NaN
             2263058              NaN              NaN              NaN
             2263059              NaN              NaN              NaN
             162903               NaN              NaN              NaN
             446092               NaN              NaN              NaN

                     official_name:uk official_name:yi old_short_name  \
element_type osmid
relation     226149               NaN              NaN            NaN
             2263058              NaN              NaN            NaN
             2263059              NaN              NaN            NaN
             162903               NaN              NaN            NaN
             446092               NaN              NaN            NaN

                     old_short_name:en old_short_name:ru short_name:ru  \
element_type osmid
relation     226149                NaN               NaN           NaN
             2263058               NaN               NaN           NaN
             2263059               NaN               NaN           NaN
             162903                NaN               NaN           NaN
             446092                NaN               NaN           NaN

                     source:start_date
element_type osmid
relation     226149                NaN
             2263058               NaN
             2263059               NaN
             162903                NaN
             446092                NaN

[5 rows x 550 columns]

In [31]:
filtered_gdf_msk.name.unique()

array(['Западный административный округ',
       'Новомосковский административный округ',
       'Троицкий административный округ',
       'Северный административный округ',
       'Северо-Западный административный округ',
       'Зеленоградский административный округ',
       'Северо-Восточный административный округ',
       'Юго-Восточный административный округ',
       'Южный административный округ',
       'Юго-Западный административный округ',
       'Восточный административный округ',
       'Центральный административный округ'], dtype=object)

In [32]:
filtered_gdf_msk[['geometry', 'addr:region', 'name']].head(5)

                                                               geometry  \
element_type osmid
relation     226149   MULTIPOLYGON (((36.90808 55.74875, 36.90939 55...
             2263058  POLYGON ((37.08750 55.59055, 37.08794 55.59070...
             2263059  MULTIPOLYGON (((36.90075 55.31486, 36.90128 55...
             162903   MULTIPOLYGON (((37.36986 55.90820, 37.36862 55...
             446092   POLYGON ((37.33566 55.84525, 37.33300 55.84528...

                     addr:region                                    name
element_type osmid
relation     226149       Москва         Западный административный округ
             2263058      Москва   Новомосковский административный округ
             2263059      Москва         Троицкий административный округ
             162903       Москва         Северный административный округ
             446092       Москва  Северо-Западный административный округ

## Казань

In [33]:
%%time
stp_districts_gdf_kzn = get_districts("Kazan, Russia")

C:\Users\elysi\AppData\Local\Temp\ipykernel_16884\3003042763.py:14: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  gdf = ox.geometries_from_place(city_name, tags={'boundary': 'administrative', 'admin_level': '9'})

CPU times: total: 1.16 s
Wall time: 1.88 s

In [34]:
stp_districts_gdf_kzn.shape

(155, 68)

In [35]:
stp_districts_gdf_kzn.head(5)

                      addr:country addr:region admin_level name name:ba  \
element_type osmid
way          46770002          NaN         NaN           6  NaN     NaN
             46770004          NaN         NaN           6  NaN     NaN
             46770005          NaN         NaN           6  NaN     NaN
             46770006          NaN         NaN           6  NaN     NaN
             75210370          NaN         NaN           9  NaN     NaN

                      name:ca name:cs name:cv name:de name:en  ... name:ce  \
element_type osmid                                             ...
way          46770002     NaN     NaN     NaN     NaN     NaN  ...     NaN
             46770004     NaN     NaN     NaN     NaN     NaN  ...     NaN
             46770005     NaN     NaN     NaN     NaN     NaN  ...     NaN
             46770006     NaN     NaN     NaN     NaN     NaN  ...     NaN
             75210370     NaN     NaN     NaN     NaN     NaN  ...     NaN

                      name:cu name:el name:gag name:kaa name:koi name:zh-Hans  \
element_type osmid
way          46770002     NaN     NaN      NaN      NaN      NaN          NaN
             46770004     NaN     NaN      NaN      NaN      NaN          NaN
             46770005     NaN     NaN      NaN      NaN      NaN          NaN
             46770006     NaN     NaN      NaN      NaN      NaN          NaN
             75210370     NaN     NaN      NaN      NaN      NaN          NaN

                      name:zh-Hant oktmo:user type
element_type osmid
way          46770002          NaN        NaN  NaN
             46770004          NaN        NaN  NaN
             46770005          NaN        NaN  NaN
             46770006          NaN        NaN  NaN
             75210370          NaN        NaN  NaN

[5 rows x 68 columns]

In [36]:
columns_gdf = stp_districts_gdf_kzn.columns.to_list()

In [37]:
stp_districts_gdf_kzn.admin_level.value_counts()

6    107
9     24
8     23
4      1
Name: admin_level, dtype: int64

In [38]:
districts_polygons_gdf_kzn = stp_districts_gdf_kzn[(stp_districts_gdf_kzn.geometry.type == 'Polygon') | (stp_districts_gdf_kzn.geometry.type == 'MultiPolygon')]

In [39]:
districts_polygons_gdf_kzn.shape

(29, 68)

In [40]:
districts_polygons_gdf_kzn.head(5)

                    addr:country addr:region admin_level  \
element_type osmid
relation     79374            RU         NaN           4
             367666          NaN         NaN           6
             367667           RU   Татарстан           6
             367668          NaN         NaN           6
             367669          NaN         NaN           6

                                       name                 name:ba  \
element_type osmid
relation     79374                Татарстан  Татарстан Республикаһы
             367666  городской округ Казань                     NaN
             367667     Высокогорский район                     NaN
             367668     Пестречинский район                     NaN
             367669        Лаишевский район                     NaN

                                     name:ca    name:cs    name:cv    name:de  \
element_type osmid
relation     79374                 Tatarstan  Tatarstán  Тутарстан  Tatarstan
             367666  districte urbà de Kazan        NaN        NaN        NaN
             367667                      NaN        NaN        NaN        NaN
             367668                      NaN        NaN        NaN        NaN
             367669                      NaN        NaN        NaN        NaN

                                    name:en  ...      name:ce     name:cu  \
element_type osmid                           ...
relation     79374                Tatarstan  ...  ГӀезалойчоь  Татарстанъ
             367666                     NaN  ...          NaN         NaN
             367667   Vysokogorsky District  ...          NaN         NaN
             367668  Pestrechinsky District  ...          NaN         NaN
             367669     Laishevsky District  ...          NaN         NaN

                       name:el   name:gag   name:kaa name:koi name:zh-Hans  \
element_type osmid
relation     79374   Ταταρστάν  Tatarstan  Tatarstan  Тотарму      鞑靼斯坦共和国
             367666        NaN        NaN        NaN      NaN          NaN
             367667        NaN        NaN        NaN      NaN          NaN
             367668        NaN        NaN        NaN      NaN          NaN
             367669        NaN        NaN        NaN      NaN          NaN

                    name:zh-Hant oktmo:user      type
element_type osmid
relation     79374       韃靼斯坦共和國   92000000  boundary
             367666          NaN        NaN  boundary
             367667          NaN        NaN  boundary
             367668          NaN        NaN  boundary
             367669          NaN        NaN  boundary

[5 rows x 68 columns]

In [41]:
filtered_gdf_kzn = districts_polygons_gdf_kzn[districts_polygons_gdf_kzn['name'].fillna('').str.contains('район')]

In [42]:
#filtered_gdf_kzn =  filtered_gdf_kzn[~filtered_gdf_kzn['addr:region'].fillna('').str.contains('Татарстан')]

In [43]:
#Вахитовский, Приволжский, Советский, Кировский, Московский, Ново-Савиновский, Авиастроительный.

In [44]:
filtered_gdf_kzn = districts_polygons_gdf_kzn[
                                              (districts_polygons_gdf_kzn['name'].fillna('').str.contains('Вахитовский'))
                                             |(districts_polygons_gdf_kzn['name'].fillna('').str.contains('Приволжский'))
                                             |(districts_polygons_gdf_kzn['name'].fillna('').str.contains('Советский'))
                                             |(districts_polygons_gdf_kzn['name'].fillna('').str.contains('Кировский'))
                                             |(districts_polygons_gdf_kzn['name'].fillna('').str.contains('Московский'))
                                             |(districts_polygons_gdf_kzn['name'].fillna('').str.contains('Ново-Савиновский'))
                                             |(districts_polygons_gdf_kzn['name'].fillna('').str.contains('Авиастроительный'))
                                             
                                             ]

In [45]:
filtered_gdf_kzn.shape

(7, 68)

In [46]:
filtered_gdf_kzn

                     addr:country addr:region admin_level  \
element_type osmid
relation     2133461          NaN         NaN           9
             2133462          NaN         NaN           9
             2133463          NaN         NaN           9
             2133464          NaN         NaN           9
             2133465          NaN         NaN           9
             2133466          NaN         NaN           9
             2133467          NaN         NaN           9

                                        name name:ba name:ca name:cs name:cv  \
element_type osmid
relation     2133461  Авиастроительный район     NaN     NaN     NaN     NaN
             2133462       Вахитовский район     NaN     NaN     NaN     NaN
             2133463         Кировский район     NaN     NaN     NaN     NaN
             2133464        Московский район     NaN     NaN     NaN     NaN
             2133465  Ново-Савиновский район     NaN     NaN     NaN     NaN
             2133466       Приволжский район     NaN     NaN     NaN     NaN
             2133467         Советский район     NaN     NaN     NaN     NaN

                     name:de name:en  ... name:ce name:cu name:el name:gag  \
element_type osmid                    ...
relation     2133461     NaN     NaN  ...     NaN     NaN     NaN      NaN
             2133462     NaN     NaN  ...     NaN     NaN     NaN      NaN
             2133463     NaN     NaN  ...     NaN     NaN     NaN      NaN
             2133464     NaN     NaN  ...     NaN     NaN     NaN      NaN
             2133465     NaN     NaN  ...     NaN     NaN     NaN      NaN
             2133466     NaN     NaN  ...     NaN     NaN     NaN      NaN
             2133467     NaN     NaN  ...     NaN     NaN     NaN      NaN

                     name:kaa name:koi name:zh-Hans name:zh-Hant oktmo:user  \
element_type osmid
relation     2133461      NaN      NaN          NaN          NaN        NaN
             2133462      NaN      NaN          NaN          NaN        NaN
             2133463      NaN      NaN          NaN          NaN        NaN
             2133464      NaN      NaN          NaN          NaN        NaN
             2133465      NaN      NaN          NaN          NaN        NaN
             2133466      NaN      NaN          NaN          NaN        NaN
             2133467      NaN      NaN          NaN          NaN        NaN

                          type
element_type osmid
relation     2133461  boundary
             2133462  boundary
             2133463  boundary
             2133464  boundary
             2133465  boundary
             2133466  boundary
             2133467  boundary

[7 rows x 68 columns]

In [47]:
filtered_gdf_kzn[filtered_gdf_kzn['name'].str.contains('район')].name.unique()

array(['Авиастроительный район', 'Вахитовский район', 'Кировский район',
       'Московский район', 'Ново-Савиновский район', 'Приволжский район',
       'Советский район'], dtype=object)

In [48]:
filtered_gdf_kzn[['geometry', 'addr:region', 'name']].head(5)

                                                               geometry  \
element_type osmid
relation     2133461  MULTIPOLYGON (((49.02084 55.90326, 49.02248 55...
             2133462  POLYGON ((49.01248 55.74849, 49.01721 55.75921...
             2133463  POLYGON ((48.83905 55.78565, 48.83912 55.78609...
             2133464  POLYGON ((48.92706 55.87345, 48.92749 55.87398...
             2133465  POLYGON ((49.08539 55.84394, 49.09775 55.84520...

                     addr:region                    name
element_type osmid
relation     2133461         NaN  Авиастроительный район
             2133462         NaN       Вахитовский район
             2133463         NaN         Кировский район
             2133464         NaN        Московский район
             2133465         NaN  Ново-Савиновский район

## Ekaterinburg

In [50]:
%%time
stp_districts_gdf_ekb = get_districts("Ekaterinburg, Russia")

C:\Users\elysi\AppData\Local\Temp\ipykernel_16884\3003042763.py:14: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  gdf = ox.geometries_from_place(city_name, tags={'boundary': 'administrative', 'admin_level': '9'})

CPU times: total: 2.73 s
Wall time: 7.99 s

In [51]:
stp_districts_gdf_ekb.shape

(89, 49)

In [52]:
stp_districts_gdf_ekb.head(5)

                      addr:country addr:region admin_level alt_name:en name  \
element_type osmid
way          61396061          NaN         NaN           5         NaN  NaN
             61396062          NaN         NaN           5         NaN  NaN
             65089463          NaN         NaN           5         NaN  NaN
             65091290          NaN         NaN           6         NaN  NaN
             65091338          NaN         NaN           5         NaN  NaN

                      name:ar name:ca name:cs name:de name:en  ... ways  \
element_type osmid                                             ...
way          61396061     NaN     NaN     NaN     NaN     NaN  ...  nan
             61396062     NaN     NaN     NaN     NaN     NaN  ...  nan
             65089463     NaN     NaN     NaN     NaN     NaN  ...  nan
             65091290     NaN     NaN     NaN     NaN     NaN  ...  nan
             65091338     NaN     NaN     NaN     NaN     NaN  ...  nan

                      ISO3166-2 gost_7.67-2003 int_ref type old_name  \
element_type osmid
way          61396061       NaN            NaN     NaN  NaN      NaN
             61396062       NaN            NaN     NaN  NaN      NaN
             65089463       NaN            NaN     NaN  NaN      NaN
             65091290       NaN            NaN     NaN  NaN      NaN
             65091338       NaN            NaN     NaN  NaN      NaN

                      oktmo:user short_name:be short_name:ru short_name:uk
element_type osmid
way          61396061        NaN           NaN           NaN           NaN
             61396062        NaN           NaN           NaN           NaN
             65089463        NaN           NaN           NaN           NaN
             65091290        NaN           NaN           NaN           NaN
             65091338        NaN           NaN           NaN           NaN

[5 rows x 49 columns]

In [53]:
columns_gdf = stp_districts_gdf_ekb.columns.to_list()

In [54]:
stp_districts_gdf_ekb.admin_level.value_counts()

6    38
9    26
5    23
4     1
3     1
Name: admin_level, dtype: int64

In [55]:
districts_polygons_gdf_ekb = stp_districts_gdf_ekb[(stp_districts_gdf_ekb.geometry.type == 'Polygon') | (stp_districts_gdf_ekb.geometry.type == 'MultiPolygon')]

In [56]:
districts_polygons_gdf_ekb.shape

(23, 49)

In [57]:
districts_polygons_gdf_ekb.head(5)

                     addr:country           addr:region admin_level  \
element_type osmid
relation     79379             RU                   NaN           4
             1019865           RU  Свердловская область           6
             1059796           RU  Свердловская область           6
             1104258           RU  Свердловская область           6
             1110855           RU  Свердловская область           6

                     alt_name:en                          name  \
element_type osmid
relation     79379           NaN          Свердловская область
             1019865         NaN    Белоярский городской округ
             1059796         NaN   Берёзовский городской округ
             1104258         NaN  городской округ Екатеринбург
             1110855         NaN     Полевской городской округ

                                name:ar                          name:ca  \
element_type osmid
relation     79379    أوبلاست سفردلوفسك          Província de Sverdlovsk
             1019865                NaN                              NaN
             1059796                NaN                              NaN
             1104258  بلدية يكاترينبورغ  Districte urbà de Iekaterinburg
             1110855                NaN                              NaN

                                 name:cs            name:de  \
element_type osmid
relation     79379    Sverdlovská oblast  Oblast Swerdlowsk
             1019865                 NaN                NaN
             1059796                 NaN                NaN
             1104258                 NaN                NaN
             1110855                 NaN                NaN

                                         name:en  ...  \
element_type osmid                                ...
relation     79379             Sverdlovsk Oblast  ...
             1019865                         NaN  ...
             1059796                         NaN  ...
             1104258  Yekaterinburg Municipality  ...
             1110855                         NaN  ...

                                                                   ways  \
element_type osmid
relation     79379    [245468547, 61498141, 69655717, 68134313, 7095...
             1019865  [542472327, 61396061, 102620363, 61396062, 868...
             1059796  [86878283, 61395634, 86872733, 86872743, 38905...
             1104258  [87279165, 102620363, 61396062, 389056521, 919...
             1110855  [70278208, 311991368, 231528544, 231528548, 64...

                     ISO3166-2 gost_7.67-2003 int_ref      type  \
element_type osmid
relation     79379      RU-SVE        РОФ-СВЕ  RU-SVE  boundary
             1019865       NaN            NaN     NaN  boundary
             1059796       NaN            NaN     NaN  boundary
             1104258       NaN            NaN     NaN  boundary
             1110855       NaN            NaN     NaN  boundary

                              old_name oktmo:user short_name:be short_name:ru  \
element_type osmid
relation     79379                 NaN        NaN           NaN           NaN
             1019865  Белоярский район        NaN           NaN           NaN
             1059796               NaN   65731000           NaN           NaN
             1104258               NaN   65701000           NaN           NaN
             1110855               NaN        NaN           NaN           NaN

                     short_name:uk
element_type osmid
relation     79379             NaN
             1019865           NaN
             1059796           NaN
             1104258           NaN
             1110855           NaN

[5 rows x 49 columns]

In [58]:
filtered_gdf_ekb = districts_polygons_gdf_ekb[districts_polygons_gdf_ekb['name'].fillna('').str.contains('район')]

In [104]:
#filtered_gdf_ekb =  filtered_gdf_ekb[~filtered_gdf_ekb['addr:region'].fillna('').str.contains('Татарстан')]

In [ ]:
#Вахитовский, Приволжский, Советский, Кировский, Московский, Ново-Савиновский, Авиастроительный.

In [62]:
filtered_gdf_ekb.shape

(8, 49)

In [63]:
filtered_gdf_ekb.head(5)

                     addr:country addr:region admin_level       alt_name:en  \
element_type osmid
relation     5803327          NaN         NaN           9               NaN
             5803648          NaN         NaN           9  October District
             5817295          NaN         NaN           9               NaN
             5817698          NaN         NaN           9    Lenin District
             5818883          NaN         NaN           9               NaN

                                     name name:ar name:ca name:cs name:de  \
element_type osmid
relation     5803327  Верх-Исетский район     NaN     NaN     NaN     NaN
             5803648    Октябрьский район     NaN     NaN     NaN     NaN
             5817295     Чкаловский район     NaN     NaN     NaN     NaN
             5817698      Ленинский район     NaN     NaN     NaN     NaN
             5818883      Кировский район     NaN     NaN     NaN     NaN

                                  name:en  ...  \
element_type osmid                         ...
relation     5803327                  NaN  ...
             5803648  Oktyabrsky District  ...
             5817295                  NaN  ...
             5817698    Leninsky District  ...
             5818883                  NaN  ...

                                                                   ways  \
element_type osmid
relation     5803327  [1051929723, 1051929726, 1051929724, 388144202...
             5803648  [389021739, 389021738, 389056527, 102620363, 8...
             5817295  [388995507, 388995506, 1225638374, 1225638369,...
             5817698  [388158360, 1231934188, 388995507, 389021739, ...
             5818883  [389021738, 388158358, 389056525, 389056517, 3...

                     ISO3166-2 gost_7.67-2003 int_ref      type old_name  \
element_type osmid
relation     5803327       NaN            NaN     NaN  boundary      NaN
             5803648       NaN            NaN     NaN  boundary      NaN
             5817295       NaN            NaN     NaN  boundary      NaN
             5817698       NaN            NaN     NaN  boundary      NaN
             5818883       NaN            NaN     NaN  boundary      NaN

                     oktmo:user short_name:be short_name:ru short_name:uk
element_type osmid
relation     5803327        NaN           NaN           NaN           NaN
             5803648        NaN           NaN           NaN           NaN
             5817295        NaN           NaN           NaN           NaN
             5817698        NaN           NaN           NaN           NaN
             5818883        NaN           NaN           NaN           NaN

[5 rows x 49 columns]

In [61]:
filtered_gdf_ekb[['geometry', 'addr:region', 'name']].head(5)

                                                               geometry  \
element_type osmid
relation     5803327  POLYGON ((60.01103 56.80777, 60.01108 56.80774...
             5803648  POLYGON ((60.61146 56.83923, 60.61162 56.83927...
             5817295  POLYGON ((60.16854 56.74734, 60.17053 56.74726...
             5817698  POLYGON ((60.50303 56.75753, 60.50663 56.75812...
             5818883  POLYGON ((60.60165 56.84262, 60.60326 56.84341...

                     addr:region                 name
element_type osmid
relation     5803327         NaN  Верх-Исетский район
             5803648         NaN    Октябрьский район
             5817295         NaN     Чкаловский район
             5817698         NaN      Ленинский район
             5818883         NaN      Кировский район

Академический[2], Верх-Исетский, Железнодорожный, Кировский, Ленинский, Октябрьский, Орджоникидзевский, Чкаловский

In [64]:
filtered_gdf_ekb[filtered_gdf_ekb['name'].str.contains('район')].name.unique()

array(['Верх-Исетский район', 'Октябрьский район', 'Чкаловский район',
       'Ленинский район', 'Кировский район', 'Железнодорожный район',
       'Орджоникидзевский район', 'Академический район'], dtype=object)

## Novosibirsk

In [65]:
%%time
stp_districts_gdf_nvsb = get_districts("Novosibirsk, Russia")

C:\Users\elysi\AppData\Local\Temp\ipykernel_16884\3003042763.py:14: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  gdf = ox.geometries_from_place(city_name, tags={'boundary': 'administrative', 'admin_level': '9'})

CPU times: total: 2.66 s
Wall time: 9.91 s

In [66]:
stp_districts_gdf_nvsb.shape

(127, 107)

In [67]:
stp_districts_gdf_nvsb.head(5)

                      admin_level                  name name:ar name:az  \
element_type osmid
way          23336207           9         улица Есенина     NaN     NaN
             25967638           9  Гусинобродское шоссе     NaN     NaN
             46480538           9                   NaN     NaN     NaN
             46481296           9                   NaN     NaN     NaN
             46481297           9                   NaN     NaN     NaN

                      name:be name:ca name:cs name:de name:el name:en  ...  \
element_type osmid                                                     ...
way          23336207     NaN     NaN     NaN     NaN     NaN     NaN  ...
             25967638     NaN     NaN     NaN     NaN     NaN     NaN  ...
             46480538     NaN     NaN     NaN     NaN     NaN     NaN  ...
             46481296     NaN     NaN     NaN     NaN     NaN     NaN  ...
             46481297     NaN     NaN     NaN     NaN     NaN     NaN  ...

                      name:sr name:sw name:tg name:tt timezone type  \
element_type osmid
way          23336207     NaN     NaN     NaN     NaN      NaN  NaN
             25967638     NaN     NaN     NaN     NaN      NaN  NaN
             46480538     NaN     NaN     NaN     NaN      NaN  NaN
             46481296     NaN     NaN     NaN     NaN      NaN  NaN
             46481297     NaN     NaN     NaN     NaN      NaN  NaN

                      short_name short_name:be short_name:ru short_name:uk
element_type osmid
way          23336207        NaN           NaN           NaN           NaN
             25967638        NaN           NaN           NaN           NaN
             46480538        NaN           NaN           NaN           NaN
             46481296        NaN           NaN           NaN           NaN
             46481297        NaN           NaN           NaN           NaN

[5 rows x 107 columns]

In [68]:
columns_gdf = stp_districts_gdf_nvsb.columns.to_list()

In [69]:
stp_districts_gdf_nvsb.admin_level.value_counts()

6    50
9    48
8    27
4     1
3     1
Name: admin_level, dtype: int64

In [70]:
districts_polygons_gdf_nvsb = stp_districts_gdf_nvsb[(stp_districts_gdf_nvsb.geometry.type == 'Polygon') | (stp_districts_gdf_nvsb.geometry.type == 'MultiPolygon')]

In [71]:
districts_polygons_gdf_nvsb.shape

(30, 107)

In [72]:
districts_polygons_gdf_nvsb.head(5)

                    admin_level                   name              name:ar  \
element_type osmid
relation     140294           4  Новосибирская область  نوفوسيبيرسك أوبلاست
             364762           9      Калининский район                  NaN
             364763           9      Центральный район                  NaN
             364764           9      Октябрьский район                  NaN
             364776           9      Дзержинский район                  NaN

                                  name:az                 name:be  \
element_type osmid
relation     140294  Novosibirsk vilayəti  Новасібірская вобласць
             364762                   NaN                     NaN
             364763                   NaN                     NaN
             364764                   NaN                     NaN
             364776                   NaN                     NaN

                                      name:ca              name:cs  \
element_type osmid
relation     140294  Província de Novosibirsk  Novosibirská oblast
             364762                       NaN                  NaN
             364763                       NaN                  NaN
             364764                       NaN                  NaN
             364776                       NaN                  NaN

                                name:de                  name:el  \
element_type osmid
relation     140294  Oblast Nowosibirsk  Περιφέρεια Νοβοσιμπίρσκ
             364762                 NaN                      NaN
             364763                 NaN                      NaN
             364764                 NaN                      NaN
             364776                 NaN                      NaN

                                name:en  ...              name:sr  \
element_type osmid                       ...
relation     140294  Novosibirsk Oblast  ...  Новосибирска област
             364762                 NaN  ...                  NaN
             364763                 NaN  ...                  NaN
             364764                 NaN  ...                  NaN
             364776                 NaN  ...                  NaN

                                name:sw              name:tg  \
element_type osmid
relation     140294  Novosibirsk Oblast  Вилояти Новосибирск
             364762                 NaN                  NaN
             364763                 NaN                  NaN
             364764                 NaN                  NaN
             364776                 NaN                  NaN

                                name:tt          timezone      type  \
element_type osmid
relation     140294  Новосибирск өлкәсе  Asia/Novosibirsk  boundary
             364762                 NaN               NaN  boundary
             364763                 NaN               NaN  boundary
             364764                 NaN               NaN  boundary
             364776                 NaN               NaN  boundary

                    short_name short_name:be short_name:ru short_name:uk
element_type osmid
relation     140294        NaN           NaN           NaN           NaN
             364762        NaN           NaN           NaN           NaN
             364763        NaN           NaN           NaN           NaN
             364764        NaN           NaN           NaN           NaN
             364776        NaN           NaN           NaN           NaN

[5 rows x 107 columns]

In [73]:
filtered_gdf_nvsb = districts_polygons_gdf_nvsb[districts_polygons_gdf_nvsb['name'].fillna('').str.contains('район')]

In [104]:
#filtered_gdf_nvsb =  filtered_gdf_nvsb[~filtered_gdf_nvsb['addr:region'].fillna('').str.contains('Татарстан')]

In [74]:
filtered_gdf_nvsb.shape

(11, 107)

In [75]:
filtered_gdf_nvsb

                     admin_level                   name name:ar name:az  \
element_type osmid
relation     364762            9      Калининский район     NaN     NaN
             364763            9      Центральный район     NaN     NaN
             364764            9      Октябрьский район     NaN     NaN
             364776            9      Дзержинский район     NaN     NaN
             365341            9  Железнодорожный район     NaN     NaN
             365385            9     Заельцовский район     NaN     NaN
             365401            9        Ленинский район     NaN     NaN
             365403            9        Кировский район     NaN     NaN
             366519            9        Советский район     NaN     NaN
             366541            9     Первомайский район     NaN     NaN
             1074003           6    Новосибирский район     NaN     NaN

                     name:be name:ca name:cs name:de name:el  \
element_type osmid
relation     364762      NaN     NaN     NaN     NaN     NaN
             364763      NaN     NaN     NaN     NaN     NaN
             364764      NaN     NaN     NaN     NaN     NaN
             364776      NaN     NaN     NaN     NaN     NaN
             365341      NaN     NaN     NaN     NaN     NaN
             365385      NaN     NaN     NaN     NaN     NaN
             365401      NaN     NaN     NaN     NaN     NaN
             365403      NaN     NaN     NaN     NaN     NaN
             366519      NaN     NaN     NaN     NaN     NaN
             366541      NaN     NaN     NaN     NaN     NaN
             1074003     NaN     NaN     NaN     NaN     NaN

                                    name:en  ... name:sr name:sw name:tg  \
element_type osmid                           ...
relation     364762                     NaN  ...     NaN     NaN     NaN
             364763                     NaN  ...     NaN     NaN     NaN
             364764                     NaN  ...     NaN     NaN     NaN
             364776                     NaN  ...     NaN     NaN     NaN
             365341                     NaN  ...     NaN     NaN     NaN
             365385                     NaN  ...     NaN     NaN     NaN
             365401                     NaN  ...     NaN     NaN     NaN
             365403                     NaN  ...     NaN     NaN     NaN
             366519                     NaN  ...     NaN     NaN     NaN
             366541                     NaN  ...     NaN     NaN     NaN
             1074003  Novosibirsky District  ...     NaN     NaN     NaN

                     name:tt timezone      type short_name short_name:be  \
element_type osmid
relation     364762      NaN      NaN  boundary        NaN           NaN
             364763      NaN      NaN  boundary        NaN           NaN
             364764      NaN      NaN  boundary        NaN           NaN
             364776      NaN      NaN  boundary        NaN           NaN
             365341      NaN      NaN  boundary        NaN           NaN
             365385      NaN      NaN  boundary        NaN           NaN
             365401      NaN      NaN  boundary        NaN           NaN
             365403      NaN      NaN  boundary        NaN           NaN
             366519      NaN      NaN  boundary        NaN           NaN
             366541      NaN      NaN  boundary        NaN           NaN
             1074003     NaN      NaN  boundary        NaN           NaN

                     short_name:ru short_name:uk
element_type osmid
relation     364762            NaN           NaN
             364763            NaN           NaN
             364764            NaN           NaN
             364776            NaN           NaN
             365341            NaN           NaN
             365385            NaN           NaN
             365401            NaN           NaN
             365403            NaN           NaN
             366519            NaN           NaN
             366541            NaN           NaN
             1074003           NaN           NaN

[11 rows x 107 columns]

In [77]:
filtered_gdf_nvsb.name.unique()

array(['Калининский район', 'Центральный район', 'Октябрьский район',
       'Дзержинский район', 'Железнодорожный район', 'Заельцовский район',
       'Ленинский район', 'Кировский район', 'Советский район',
       'Первомайский район', 'Новосибирский район'], dtype=object)


№	Район	Площадь,
км²	Население,
чел.
(2021)	Код
ОКАТО
1	Дзержинский район	36,5	↘153 688[5]	50 401 364
2	Железнодорожный район	8,3	↘62 242[5]	50 401 368
3	Заельцовский район	83,0	↘148 873[5]	50 401 372
4	Калининский район	46,2	↗201 878[5]	50 401 373
5	Кировский район	52,0	↗193 808[5]	50 401 374
6	Ленинский район	70,3	↗316 728[5]	50 401 377
7	Октябрьский район	57,6	↗254 290[5]	50 401 379
8	Первомайский район	71,7	↗90 291[5]	50 401 382
9	Советский район	89,2	↘135 355[5]	50 401 384
10	Центральный район	6,4	↘76 442[5]	50 401 386

In [78]:
filtered_gdf_nvsb[['geometry', 'addr:region', 'name']].head(5)

                                                              geometry  \
element_type osmid
relation     364762  MULTIPOLYGON (((82.92842 55.18488, 82.92885 55...
             364763  POLYGON ((82.91138 55.04914, 82.91240 55.04939...
             364764  POLYGON ((82.91843 55.00962, 82.92282 55.01332...
             364776  POLYGON ((82.94283 55.05420, 82.94361 55.05433...
             365341  POLYGON ((82.87451 55.03162, 82.87605 55.03551...

                    addr:region                   name
element_type osmid
relation     364762         NaN      Калининский район
             364763         NaN      Центральный район
             364764         NaN      Октябрьский район
             364776         NaN      Дзержинский район
             365341         NaN  Железнодорожный район

## Krasnodar

In [79]:
%%time
stp_districts_gdf_krsn = get_districts("Krasnodar, Russia")

C:\Users\elysi\AppData\Local\Temp\ipykernel_16884\3003042763.py:14: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  gdf = ox.geometries_from_place(city_name, tags={'boundary': 'administrative', 'admin_level': '9'})

CPU times: total: 562 ms
Wall time: 4.78 s

In [80]:
stp_districts_gdf_krsn.shape

(43, 67)

In [81]:
stp_districts_gdf_krsn.head(5)

                      addr:country addr:region admin_level int_name name  \
element_type osmid
way          40988847          NaN         NaN           4      NaN  NaN
             41191209          NaN         NaN           4      NaN  NaN
             41191210          NaN         NaN           4      NaN  NaN
             46545037          NaN         NaN           6      NaN  NaN
             59391119          NaN         NaN           9      NaN  NaN

                      name:az name:ca name:de name:el name:en  ...  \
element_type osmid                                             ...
way          40988847     NaN     NaN     NaN     NaN     NaN  ...
             41191209     NaN     NaN     NaN     NaN     NaN  ...
             41191210     NaN     NaN     NaN     NaN     NaN  ...
             46545037     NaN     NaN     NaN     NaN     NaN  ...
             59391119     NaN     NaN     NaN     NaN     NaN  ...

                      name:be-tarask name:tt official_name:cs  \
element_type osmid
way          40988847            NaN     NaN              NaN
             41191209            NaN     NaN              NaN
             41191210            NaN     NaN              NaN
             46545037            NaN     NaN              NaN
             59391119            NaN     NaN              NaN

                      official_name:de official_name:en official_name:fr  \
element_type osmid
way          40988847              NaN              NaN              NaN
             41191209              NaN              NaN              NaN
             41191210              NaN              NaN              NaN
             46545037              NaN              NaN              NaN
             59391119              NaN              NaN              NaN

                      oktmo:user short_name:cs alt_name:uk full_name
element_type osmid
way          40988847        NaN           NaN         NaN       NaN
             41191209        NaN           NaN         NaN       NaN
             41191210        NaN           NaN         NaN       NaN
             46545037        NaN           NaN         NaN       NaN
             59391119        NaN           NaN         NaN       NaN

[5 rows x 67 columns]

In [82]:
columns_gdf = stp_districts_gdf_krsn.columns.to_list()

In [84]:
districts_polygons_gdf_krsn = stp_districts_gdf_krsn[(stp_districts_gdf_krsn.geometry.type == 'Polygon') | (stp_districts_gdf_krsn.geometry.type == 'MultiPolygon')]

In [87]:
districts_polygons_gdf_krsn.admin_level.value_counts()

8    6
9    4
6    3
4    2
Name: admin_level, dtype: int64

In [85]:
districts_polygons_gdf_krsn.shape

(15, 67)

In [86]:
districts_polygons_gdf_krsn.head(5)

                    addr:country addr:region admin_level        int_name  \
element_type osmid
relation     108082           RU         NaN           4  Krasnodar Krai
             253256           RU         NaN           4             NaN
             269701          NaN         NaN           6             NaN
             365285          NaN         NaN           6             NaN
             916830          NaN         NaN           9             NaN

                                          name           name:az  \
element_type osmid
relation     108082         Краснодарский край  Krasnodar diyarı
             253256                     Адыгея            Adıgey
             269701  городской округ Краснодар               NaN
             365285       Тахтамукайский район               NaN
             916830          Карасунский округ               NaN

                                         name:ca           name:de   name:el  \
element_type osmid
relation     108082                          NaN               NaN       NaN
             253256                    Adiguèsia           Adygeja  Αντιγκέα
             269701  Districte urbà de Krasnodar               NaN       NaN
             365285                          NaN               NaN       NaN
             916830                          NaN  Bezirk Krasnodar       NaN

                                     name:en  ... name:be-tarask  \
element_type osmid                            ...
relation     108082                      NaN  ...            NaN
             253256       Republic of Adygea  ...         Адыгея
             269701   Krasnodar Municipality  ...            NaN
             365285  Takhtamukaysky District  ...            NaN
             916830                      NaN  ...            NaN

                                 name:tt   official_name:cs  official_name:de  \
element_type osmid
relation     108082                  NaN                NaN               NaN
             253256  Адыгея Республикасы  Republika Adygsko  Republik Adygeja
             269701                  NaN                NaN               NaN
             365285                  NaN                NaN               NaN
             916830                  NaN                NaN               NaN

                       official_name:en      official_name:fr oktmo:user  \
element_type osmid
relation     108082                 NaN                   NaN        NaN
             253256  Republic of Adygea  République d'Adyguée   79000000
             269701                 NaN                   NaN        NaN
             365285                 NaN                   NaN        NaN
             916830                 NaN                   NaN        NaN

                    short_name:cs                alt_name:uk  \
element_type osmid
relation     108082           NaN                        NaN
             253256     Adygejsko                        NaN
             269701           NaN  міський округ Катеринодар
             365285           NaN                        NaN
             916830           NaN                        NaN

                                                             full_name
element_type osmid
relation     108082                                                NaN
             253256                                                NaN
             269701  Муниципальное образование городской округ горо...
             365285                                                NaN
             916830                                                NaN

[5 rows x 67 columns]

In [88]:
districts_polygons_gdf_krsn.name.unique()

array(['Краснодарский край', 'Адыгея', 'городской округ Краснодар',
       'Тахтамукайский район', 'Карасунский округ', 'Прикубанский округ',
       'Центральный округ', 'Западный округ', 'Теучежский район',
       'Афипсипское сельское поселение', 'Козетское сельское поселение',
       'Старобжегокайское сельское поселение',
       'Тахтамукайское сельское поселение',
       'Яблоновское городское поселение',
       'Тлюстенхабльское городское поселение'], dtype=object)

	Внутригородской
округ	Площадь
(км²)[6][7]	Общее
население[6]
(чел.)	Городское
население[8]
(чел.)
	Западный	22,0	↘196 443[9]	↘196 443[9]
	Карасунский	152,0	↗354 313[9]	↗313 456[9]
	Прикубанский	474,0	↗481 953[9]	↗417 875[9]
	Центральный	28,5	↗193 517[9]	↗193 517[9]

In [95]:
filtered_gdf_krsn = districts_polygons_gdf_krsn[districts_polygons_gdf_krsn['name'].fillna('').str.contains('округ')]

In [96]:
filtered_gdf_krsn = filtered_gdf_krsn[~filtered_gdf_krsn['name'].fillna('').str.contains('городской округ Краснодар')]

In [97]:
filtered_gdf_krsn.shape

(4, 67)

In [98]:
filtered_gdf_krsn

                    addr:country addr:region admin_level int_name  \
element_type osmid
relation     916830          NaN         NaN           9      NaN
             916831          NaN         NaN           9      NaN
             916832          NaN         NaN           9      NaN
             916833          NaN         NaN           9      NaN

                                   name name:az name:ca           name:de  \
element_type osmid
relation     916830   Карасунский округ     NaN     NaN  Bezirk Krasnodar
             916831  Прикубанский округ     NaN     NaN               NaN
             916832   Центральный округ     NaN     NaN               NaN
             916833      Западный округ     NaN     NaN               NaN

                    name:el name:en  ... name:be-tarask name:tt  \
element_type osmid                   ...
relation     916830     NaN     NaN  ...            NaN     NaN
             916831     NaN     NaN  ...            NaN     NaN
             916832     NaN     NaN  ...            NaN     NaN
             916833     NaN     NaN  ...            NaN     NaN

                    official_name:cs official_name:de official_name:en  \
element_type osmid
relation     916830              NaN              NaN              NaN
             916831              NaN              NaN              NaN
             916832              NaN              NaN              NaN
             916833              NaN              NaN              NaN

                    official_name:fr oktmo:user short_name:cs alt_name:uk  \
element_type osmid
relation     916830              NaN        NaN           NaN         NaN
             916831              NaN        NaN           NaN         NaN
             916832              NaN        NaN           NaN         NaN
             916833              NaN        NaN           NaN         NaN

                    full_name
element_type osmid
relation     916830       NaN
             916831       NaN
             916832       NaN
             916833       NaN

[4 rows x 67 columns]

In [100]:
filtered_gdf_krsn.name.unique()

array(['Карасунский округ', 'Прикубанский округ', 'Центральный округ',
       'Западный округ'], dtype=object)

In [101]:
filtered_gdf_krsn[['geometry', 'addr:region', 'name']].head(5)

                                                              geometry  \
element_type osmid
relation     916830  POLYGON ((39.02333 45.03474, 39.02637 45.03397...
             916831  POLYGON ((38.64902 45.06338, 38.64786 45.06587...
             916832  POLYGON ((38.97881 45.01039, 38.97860 45.01170...
             916833  POLYGON ((38.90942 45.04445, 38.91247 45.04421...

                    addr:region                name
element_type osmid
relation     916830         NaN   Карасунский округ
             916831         NaN  Прикубанский округ
             916832         NaN   Центральный округ
             916833         NaN      Западный округ

## Делаем ГеоСПБ

In [105]:
%%time
stp_districts_gdf_spb = get_districts("Saint Petersburg, Russia")

C:\Users\elysi\AppData\Local\Temp\ipykernel_16884\3003042763.py:14: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  gdf = ox.geometries_from_place(city_name, tags={'boundary': 'administrative', 'admin_level': '9'})

CPU times: total: 2.47 s
Wall time: 5.01 s

In [106]:
stp_districts_gdf_spb.shape

(1355, 206)

In [107]:
stp_districts_gdf_spb.head(5)

                          highway  \
element_type osmid
way          4455867      service
             4456380  residential
             4459534    secondary
             4460101          NaN
             4462595  residential

                                                               geometry  \
element_type osmid
way          4455867  LINESTRING (30.33015 59.98484, 30.32961 59.984...
             4456380  LINESTRING (30.21386 59.83934, 30.21410 59.839...
             4459534  LINESTRING (30.43335 60.01507, 30.43318 60.015...
             4460101  LINESTRING (30.26800 60.03830, 30.26781 60.037...
             4462595  LINESTRING (30.31233 59.92923, 30.31225 59.929...

                            boundary  ref addr:country addr:region  \
element_type osmid
way          4455867  administrative  NaN          NaN         NaN
             4456380  administrative  NaN          NaN         NaN
             4459534  administrative  NaN          NaN         NaN
             4460101  administrative  NaN          NaN         NaN
             4462595  administrative  NaN          NaN         NaN

                                    name name:be name:ca name:cs  ...  \
element_type osmid                                                ...
way          4455867                 NaN     NaN     NaN     NaN  ...
             4456380       улица Козлова     NaN     NaN     NaN  ...
             4459534   Северный проспект     NaN     NaN     NaN  ...
             4460101                 NaN     NaN     NaN     NaN  ...
             4462595  переулок Антоненко     NaN     NaN     NaN  ...

                     old_name:mk oktmo:user contact:instagram contact:vk  \
element_type osmid
way          4455867         NaN        NaN               NaN        NaN
             4456380         NaN        NaN               NaN        NaN
             4459534         NaN        NaN               NaN        NaN
             4460101         NaN        NaN               NaN        NaN
             4462595         NaN        NaN               NaN        NaN

                     contact:website oktmo short_name:be short_name:ru  \
element_type osmid
way          4455867             NaN   NaN           NaN           NaN
             4456380             NaN   NaN           NaN           NaN
             4459534             NaN   NaN           NaN           NaN
             4460101             NaN   NaN           NaN           NaN
             4462595             NaN   NaN           NaN           NaN

                     short_name:uk admin_centre
element_type osmid
way          4455867           NaN          NaN
             4456380           NaN          NaN
             4459534           NaN          NaN
             4460101           NaN          NaN
             4462595           NaN          NaN

[5 rows x 206 columns]

In [108]:
columns_gdf = stp_districts_gdf_spb.columns.to_list()

In [109]:
districts_polygons_gdf_spb = stp_districts_gdf_spb[(stp_districts_gdf_spb.geometry.type == 'Polygon') | (stp_districts_gdf_spb.geometry.type == 'MultiPolygon')]

In [110]:
districts_polygons_gdf_spb.admin_level.value_counts()

8    98
5    17
4     2
6     2
3     1
Name: admin_level, dtype: int64

In [111]:
districts_polygons_gdf_spb.shape

(120, 206)

In [118]:
filtered_gdf_spb = districts_polygons_gdf_spb[districts_polygons_gdf_spb['name'].fillna('').str.contains('район')]

In [119]:
filtered_gdf_spb = filtered_gdf_spb[filtered_gdf_spb['addr:region'].fillna('').str.contains('Санкт-Петербург')]

In [120]:
filtered_gdf_spb.shape

(17, 206)

In [122]:
filtered_gdf_spb.name.unique()

array(['Колпинский район', 'Пушкинский район', 'Московский район',
       'Красносельский район', 'Петродворцовый район', 'Невский район',
       'Фрунзенский район', 'Адмиралтейский район',
       'Василеостровский район', 'Выборгский район', 'Калининский район',
       'Кировский район', 'Красногвардейский район', 'Центральный район',
       'Петроградский район', 'Курортный район', 'Приморский район'],
      dtype=object)

In [123]:
filtered_gdf_spb[['geometry', 'addr:region', 'name']].head(5)

                                                              geometry  \
element_type osmid
relation     337424  POLYGON ((30.44112 59.82937, 30.44333 59.82980...
             338635  POLYGON ((30.21822 59.67307, 30.21918 59.67361...
             338636  POLYGON ((30.19877 59.80161, 30.19901 59.80180...
             363103  MULTIPOLYGON (((30.06506 59.66830, 30.07331 59...
             367375  MULTIPOLYGON (((30.04477 59.86349, 30.04490 59...

                         addr:region                  name
element_type osmid
relation     337424  Санкт-Петербург      Колпинский район
             338635  Санкт-Петербург      Пушкинский район
             338636  Санкт-Петербург      Московский район
             363103  Санкт-Петербург  Красносельский район
             367375  Санкт-Петербург  Петродворцовый район

## Стакаем вместе

filtered_gdf_krsn
filtered_gdf_nvsb
filtered_gdf_ekb
filtered_gdf_kzn
filtered_gdf_msk
filtered_gdf_spb

districts_polygons_df[(districts_polygons_df['name'].str.contains('район'))
                      & (districts_polygons_df['addr:region'].str.contains('Санкт-Петербург'))]\
[['geometry', 'addr:region', 'name']]

In [124]:
geo_krsn = filtered_gdf_krsn[['geometry', 'addr:region', 'name']]
geo_nvsb = filtered_gdf_nvsb[['geometry', 'addr:region', 'name']]
geo_ekb  = filtered_gdf_ekb[['geometry', 'addr:region', 'name']]
geo_kzn  = filtered_gdf_kzn[['geometry', 'addr:region', 'name']]
geo_msk  = filtered_gdf_msk[['geometry', 'addr:region', 'name']]
geo_spb  = filtered_gdf_spb[['geometry', 'addr:region', 'name']]

In [126]:
geo_spb['city'] = 'Санкт-Петербург'
geo_msk['city'] = 'Москва'
geo_kzn['city'] = 'Казань'
geo_ekb['city'] = 'Екатеринбург'
geo_nvsb['city'] = 'Новосибирск'
geo_krsn['city'] = 'Краснодар'

D:\Anaconda\lib\site-packages\geopandas\geodataframe.py:1525: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
D:\Anaconda\lib\site-packages\geopandas\geodataframe.py:1525: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
D:\Anaconda\lib\site-packages\geopandas\geodataframe.py:1525: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
D:\Anaconda\lib\site-packages\geopandas\geodataframe.py:1525: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
D:\Anaconda\lib\site-packages\geopandas\geodataframe.py:1525: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [127]:
geo_krsn.head(4)

                                                              geometry  \
element_type osmid
relation     916830  POLYGON ((39.02333 45.03474, 39.02637 45.03397...
             916831  POLYGON ((38.64902 45.06338, 38.64786 45.06587...
             916832  POLYGON ((38.97881 45.01039, 38.97860 45.01170...
             916833  POLYGON ((38.90942 45.04445, 38.91247 45.04421...

                    addr:region                name       city
element_type osmid
relation     916830         NaN   Карасунский округ  Краснодар
             916831         NaN  Прикубанский округ  Краснодар
             916832         NaN   Центральный округ  Краснодар
             916833         NaN      Западный округ  Краснодар

In [129]:
geo_all = pd.concat([geo_spb, geo_msk, geo_kzn, geo_ekb, geo_nvsb, geo_krsn], ignore_index=True)

In [131]:
geo_all.head(5)

,geometry,addr:region,name,city
0,"POLYGON ((30.44112 59.82937, 30.44333 59.82980...",Санкт-Петербург,Колпинский район,Санкт-Петербург
1,"POLYGON ((30.21822 59.67307, 30.21918 59.67361...",Санкт-Петербург,Пушкинский район,Санкт-Петербург
2,"POLYGON ((30.19877 59.80161, 30.19901 59.80180...",Санкт-Петербург,Московский район,Санкт-Петербург
3,"MULTIPOLYGON (((30.06506 59.66830, 30.07331 59...",Санкт-Петербург,Красносельский район,Санкт-Петербург
4,"MULTIPOLYGON (((30.04477 59.86349, 30.04490 59...",Санкт-Петербург,Петродворцовый район,Санкт-Петербург

In [132]:
geo_all.to_csv('geo_all_gsom_case.csv', index = False)

In [133]:
geo_all = pd.read_csv('geo_all_gsom_case.csv')

In [134]:
geo_all.head(5)

,geometry,addr:region,name,city
0,"POLYGON ((30.4411207 59.8293735, 30.4433336 59...",Санкт-Петербург,Колпинский район,Санкт-Петербург
1,"POLYGON ((30.2182227 59.6730689, 30.219183 59....",Санкт-Петербург,Пушкинский район,Санкт-Петербург
2,"POLYGON ((30.1987721 59.8016053, 30.1990074 59...",Санкт-Петербург,Московский район,Санкт-Петербург
3,"MULTIPOLYGON (((30.0650571 59.6683027, 30.0733...",Санкт-Петербург,Красносельский район,Санкт-Петербург
4,"MULTIPOLYGON (((30.0447658 59.8634858, 30.0449...",Санкт-Петербург,Петродворцовый район,Санкт-Петербург

In [135]:
geo_all['geometry'] = gpd.GeoSeries.from_wkt(geo_all['geometry'])
geo_all_gdf = gpd.GeoDataFrame(geo_all, geometry='geometry')
geo_all_gdf.crs = "EPSG:4326"